from pathlib import Path
import re

def patch_file(path, fn):
    p=Path(path); s=p.read_text(encoding='utf-8'); s=fn(s); p.write_text(s,encoding='utf-8')

def one(s,old,new,label):
    n=s.count(old)
    if n!=1: raise SystemExit(f'{label}: expected 1, found {n}')
    return s.replace(old,new,1)

def sub(s,pat,repl,label):
    s2,n=re.subn(pat,repl,s,count=1,flags=re.S)
    if n!=1: raise SystemExit(f'{label}: expected 1, found {n}')
    return s2

def index(s):
    s=one(s,'<label class="span-2 absence-note-field">Catatan / tujuan<textarea id="absenceNote" name="note" rows="6" placeholder="Catatan tambahan jika perlu"></textarea></label>','<label class="span-2 absence-note-field">Catatan / tujuan <small>(Sila isi tajuk aktiviti yang terlibat)</small><textarea id="absenceNote" name="note" rows="6" placeholder="Contoh: Kejohanan Merentas Desa Daerah / Bengkel PPD"></textarea></label>','note helper')
    s=one(s,'<div class="pc-legend"><span><i class="legend-dot hadir"></i> Hadir</span><span><i class="legend-dot lewat"></i> Lewat</span><span><i class="legend-dot absent"></i> Tidak hadir</span></div>','<div class="pc-legend"><span><i class="legend-dot hadir"></i> Hadir</span><span><i class="legend-dot lewat"></i> Lewat / Balik Awal — waktu berkenaan merah</span><span><i class="legend-dot absent"></i> Tidak hadir</span></div>','legend')
    pairs=[
    ('<label>Kategori<select id="absencePublicCategory" onchange="applyAbsencePublicFilters()"><option value="">Semua</option><option>Pengurusan</option><option>PPP</option><option>AKP</option></select></label>','<label>Kategori<select id="absencePublicCategory" onchange="applyAbsencePublicFilters()"><option value="">Semua</option><option>Pengurusan</option><option>PPP</option><option>AKP</option></select></label><label>Susun<select id="absencePublicSort" onchange="applyAbsencePublicFilters()"><option value="date_desc">Tarikh terbaru</option><option value="date_asc">Tarikh terlama</option><option value="name_asc">Nama A–Z</option><option value="name_desc">Nama Z–A</option><option value="status_asc">Status A–Z</option></select></label>'),
    ('<label>Kategori<select id="absenceManageCategory" onchange="applyAbsenceManageFilters()"><option value="">Semua</option><option>Pengurusan</option><option>PPP</option><option>AKP</option></select></label>','<label>Kategori<select id="absenceManageCategory" onchange="applyAbsenceManageFilters()"><option value="">Semua</option><option>Pengurusan</option><option>PPP</option><option>AKP</option></select></label><label>Susun<select id="absenceManageSort" onchange="applyAbsenceManageFilters()"><option value="date_desc">Tarikh terbaru</option><option value="date_asc">Tarikh terlama</option><option value="name_asc">Nama A–Z</option><option value="name_desc">Nama Z–A</option><option value="status_asc">Status A–Z</option></select></label>'),
    ('<label>Status<select id="timeReviewStatus" onchange="applyTimeReviewFilters()"><option value="">Semua</option><option>BELUM DIAMBIL MAKLUM</option><option>DIAMBIL MAKLUM</option><option>DITOLAK</option></select></label>','<label>Status<select id="timeReviewStatus" onchange="applyTimeReviewFilters()"><option value="">Semua</option><option>BELUM DIAMBIL MAKLUM</option><option>DIAMBIL MAKLUM</option><option>DITOLAK</option></select></label><label>Susun<select id="timeReviewSort" onchange="applyTimeReviewFilters()"><option value="date_desc">Tarikh terbaru</option><option value="date_asc">Tarikh terlama</option><option value="name_asc">Nama A–Z</option><option value="name_desc">Nama Z–A</option><option value="status_asc">Status A–Z</option></select></label>'),
    ('<label>Sumber<select id="reportSourceFilter" onchange="applyReportFilters()"><option value="">Semua</option><option>GPS</option><option>TEST</option><option>ADMIN</option><option>TIDAK_HADIR</option></select></label>','<label>Sumber<select id="reportSourceFilter" onchange="applyReportFilters()"><option value="">Semua</option><option>GPS</option><option>TEST</option><option>ADMIN</option><option>TIDAK_HADIR</option></select></label><label>Susun<select id="reportSort" onchange="applyReportFilters()"><option value="name_asc">Nama A–Z</option><option value="name_desc">Nama Z–A</option><option value="status_asc">Status A–Z</option><option value="in_asc">Masuk terawal</option><option value="in_desc">Masuk terlewat</option></select></label>'),
    ('<label>PIN<select id="userPasswordFilter" onchange="applyUserFilters()"><option value="">Semua</option><option value="ready">Sedia</option><option value="temp">Perlu tetapkan semula</option><option value="unset">Belum ditetapkan</option><option value="locked">Dikunci</option></select></label>','<label>PIN<select id="userPasswordFilter" onchange="applyUserFilters()"><option value="">Semua</option><option value="ready">Sedia</option><option value="temp">Perlu tetapkan semula</option><option value="unset">Belum ditetapkan</option><option value="locked">Dikunci</option></select></label><label>Susun<select id="userSort" onchange="applyUserFilters()"><option value="name_asc">Nama A–Z</option><option value="name_desc">Nama Z–A</option><option value="category_asc">Kategori A–Z</option><option value="active_first">Aktif dahulu</option></select></label>')]
    for i,(a,b) in enumerate(pairs): s=one(s,a,b,f'sort {i}')
    s=one(s,'<th>Status</th><th>Semakan</th>','<th>Status</th><th>Tindakan / Pelulus</th>','absence heading')
    s=one(s,'<label>Sesi 1 · Waktu Masuk<input name="defaultS1In" type="time" required><small>Selepas waktu ini = LEWAT, tetapi rekod tetap diterima.</small></label>','<label>Sesi 1 · Waktu Masuk<input name="defaultS1In" type="time" required><small>Selepas waktu ini = LEWAT, selagi masih dalam had akhir masuk.</small></label><label>Had akhir Rekod Masuk Sesi 1<input name="defaultMaxPunchIn" type="time" required><small>Selepas waktu ini, Rekod Masuk Sesi 1 ditolak.</small></label>','max in UI')
    s=one(s,'<label>Sesi 2 · Waktu Keluar<input name="defaultS2Out" type="time"><small>Opsyenal. Isi bersama Waktu Masuk Sesi 2 untuk mengaktifkan 4 rakaman sehari.</small></label>','<label>Sesi 2 · Waktu Keluar<input name="defaultS2Out" type="time"><small>Opsyenal. Jika diisi, menjadi rujukan BALIK AWAL Sesi 2.</small></label><label>Pasangan Sesi 2 opsyenal<select name="allowOptionalSecondSession"><option value="TRUE">Aktif</option><option value="FALSE">Tidak aktif</option></select><small>Aktif: selepas Masuk → Balik Sesi 1, pengguna boleh rekod Masuk → Balik Sesi 2 jika ada.</small></label>','S2 UI')
    s=one(s,'<label class="span-2">Hari bekerja<input name="workingDays" placeholder="SUN,MON,TUE,WED,THU" required><small>Gunakan kod SUN, MON, TUE, WED, THU, FRI, SAT. Default Kedah: SUN–THU.</small></label>','<label class="span-2">Hari bekerja<input name="workingDays" placeholder="SUN,MON,TUE,WED,THU" required><small>Gunakan kod SUN, MON, TUE, WED, THU, FRI, SAT. Default Kedah: SUN–THU.</small></label><div class="span-2 setting-subsection"><b>WBF Khamis — AKP & Pengetua</b><small>Jika masa Masuk Sesi 1 berada dalam julat WBF, rujukan Balik Awal dikira daripada masa masuk + tempoh WBF.</small></div><label>WBF Khamis<select name="thursdayWbfEnabled"><option value="TRUE">Aktif</option><option value="FALSE">Tidak aktif</option></select></label><label>Tempoh WBF (minit)<input name="thursdayWbfDurationMinutes" type="number" min="1" max="1440" required></label><label>Masuk WBF mula<input name="thursdayWbfInFrom" type="time" required></label><label>Masuk WBF akhir<input name="thursdayWbfInTo" type="time" required></label><label>Pulang WBF mula<input name="thursdayWbfOutFrom" type="time" required></label><label>Pulang WBF akhir<input name="thursdayWbfOutTo" type="time" required></label>','WBF UI')
    return s

def scripts(s):
    s=one(s,"    const hasSecondSession=!!(b.schedule.s2In&&b.schedule.s2Out);","    const hasSecondSession=!!(b.schedule.allowSecondSession||b.schedule.s2In||b.schedule.s2Out);",'S2 detect')
    s=one(s,"    if(btnIn){btnIn.disabled=step.complete||step.type!=='IN';btnIn.textContent=step.complete?'Rekod Waktu Lengkap':'Rakam Waktu Masuk';}\n    if(btnOut){btnOut.disabled=step.complete||step.type!=='OUT';btnOut.textContent=step.complete?'Rekod Waktu Lengkap':'Rakam Waktu Balik';}","    const sessionLabel=`Sesi ${Number(step.session)||1}`;\n    if(btnIn){btnIn.disabled=step.complete||step.type!=='IN';btnIn.textContent=step.complete?'Rekod Waktu Lengkap':`Rakam Waktu Masuk · ${sessionLabel}${Number(step.session)===2?' (jika ada)':''}`;}\n    if(btnOut){btnOut.disabled=step.complete||step.type!=='OUT';btnOut.textContent=step.complete?'Rekod Waktu Lengkap':`Rakam Waktu Balik · ${sessionLabel}`;}",'button labels')
    s=sub(s,r"  function cardRowsHtml\(d,half\)\{.*?\n  \}\n  function shortTime",'''  function cardRowsHtml(d,half){
    const start=half===1?1:16,end=half===1?Math.min(15,d.daysInMonth):d.daysInMonth,byDay=new Map((d.records||[]).map(r=>[Number(r.day),r]));let html='';
    if(start>end)return '<tr><td colspan="7" class="pc-empty">Tiada tarikh untuk bahagian ini.</td></tr>';
    for(let day=start;day<=end;day++){
      const r=byDay.get(day)||{},status=String(r.status||'').trim().toUpperCase();
      const cls=status==='TIDAK HADIR'?'pc-row-absent':status==='WEEKEND'?'pc-row-weekend':(status.includes('LEWAT')||status.includes('BALIK AWAL'))?'pc-row-lewat':status==='HADIR'?'pc-row-hadir':'';
      if(status==='WEEKEND'){const label=String(r.reason||'').trim().toUpperCase()||'CUTI';html+=`<tr class="${cls}"><td class="pc-day">${day}</td><td colspan="6" class="pc-weekend-full"><span>${esc(label)}</span></td></tr>`;continue;}
      if(status==='TIDAK HADIR'){const reason=String(r.reason||'').trim(),detail=reason&&reason.toUpperCase()!=='TIDAK HADIR'?reason:'TIADA PENJELASAN';html+=`<tr class="${cls}"><td class="pc-day">${day}</td><td colspan="6" class="pc-absence-full"><span class="pc-absence-label">TIDAK HADIR</span><span class="pc-absence-reason">${esc(detail)}</span></td></tr>`;continue;}
      const reviews=r.reviewItems||[], flagged=(type,session)=>reviews.some(x=>String(x.type||'').toUpperCase()===type&&Number(x.session||1)===session), tc=(v,bad)=>`<td class="${bad?'pc-time-alert':''}">${esc(shortTime(v))}</td>`;
      html+=`<tr class="${cls}"><td class="pc-day">${day}</td>${tc(r.inTime,flagged('LEWAT',1))}${tc(r.outTime,flagged('BALIK AWAL',1))}${tc(r.inTime2,flagged('LEWAT',2))}${tc(r.outTime2,flagged('BALIK AWAL',2))}<td class="pc-statement">${esc(cardStatement(r))}</td><td class="pc-sign"></td></tr>`;
    }return html;
  }
  function shortTime''','card rows')
    helper="""\n  function compareText(a,b){return String(a??'').localeCompare(String(b??''),'ms',{numeric:true,sensitivity:'base'});}\n  function sortRecords(list,mode){const rows=(list||[]).slice(),m=String(mode||''),cmp=(a,b)=>compareText(a,b),dateOf=r=>String(r.startDate||r.date||r.submittedAt||''),statusOf=r=>String(r.reviewStatus||r.status||r.category||''),timeOf=r=>String(r.inTime||'99:99');if(m==='date_desc')return rows.sort((a,b)=>cmp(dateOf(b),dateOf(a))||cmp(a.name,b.name));if(m==='date_asc')return rows.sort((a,b)=>cmp(dateOf(a),dateOf(b))||cmp(a.name,b.name));if(m==='name_desc')return rows.sort((a,b)=>cmp(b.name,a.name));if(m==='status_asc')return rows.sort((a,b)=>cmp(statusOf(a),statusOf(b))||cmp(a.name,b.name));if(m==='category_asc')return rows.sort((a,b)=>cmp(a.category,b.category)||cmp(a.name,b.name));if(m==='active_first')return rows.sort((a,b)=>(Number(!!b.active)-Number(!!a.active))||cmp(a.name,b.name));if(m==='in_asc')return rows.sort((a,b)=>cmp(timeOf(a),timeOf(b))||cmp(a.name,b.name));if(m==='in_desc')return rows.sort((a,b)=>cmp(timeOf(b),timeOf(a))||cmp(a.name,b.name));return rows.sort((a,b)=>cmp(a.name,b.name));}\n"""
    s=one(s,'\n  // ---------- Senarai Tidak Hadir / Keberadaan (semua pengguna) ----------',helper+'\n  // ---------- Senarai Tidak Hadir / Keberadaan (semua pengguna) ----------','sort helper')
    s=one(s,"function currentAbsencePublicFilters(){return {fromDate:document.getElementById('absencePublicFrom')?.value||'',toDate:document.getElementById('absencePublicTo')?.value||'',search:String(document.getElementById('absencePublicSearch')?.value||'').trim(),mode:document.getElementById('absencePublicMode')?.value||'',status:document.getElementById('absencePublicStatus')?.value||'',category:document.getElementById('absencePublicCategory')?.value||''};}","function currentAbsencePublicFilters(){return {fromDate:document.getElementById('absencePublicFrom')?.value||'',toDate:document.getElementById('absencePublicTo')?.value||'',search:String(document.getElementById('absencePublicSearch')?.value||'').trim(),mode:document.getElementById('absencePublicMode')?.value||'',status:document.getElementById('absencePublicStatus')?.value||'',category:document.getElementById('absencePublicCategory')?.value||'',sort:document.getElementById('absencePublicSort')?.value||'date_desc'};}",'public sort state')
    s=one(s,"    return data.filter(r=>{const hay=norm([r.name,r.jobTitle,r.category,r.mode,r.type,r.startDate,r.endDate,r.startTime,r.endTime,r.status].join(' '));return(!q||hay.includes(q))&&(!f.mode||r.mode===f.mode)&&(!f.status||r.status===f.status)&&(!f.category||r.category===f.category);});","    return sortRecords(data.filter(r=>{const hay=norm([r.name,r.jobTitle,r.category,r.mode,r.type,r.startDate,r.endDate,r.startTime,r.endTime,r.status].join(' '));return(!q||hay.includes(q))&&(!f.mode||r.mode===f.mode)&&(!f.status||r.status===f.status)&&(!f.category||r.category===f.category);}),f.sort);",'public sorting')
    s=sub(s,r"  function applyAbsenceManageFilters\(\)\{.*?\n  \}",'''  function applyAbsenceManageFilters(){const data=state.absenceManagement?.requests||[],q=norm(document.getElementById('absenceManageSearch')?.value),st=document.getElementById('absenceManageStatus')?.value||'',cat=document.getElementById('absenceManageCategory')?.value||'',mode=document.getElementById('absenceManageMode')?.value||'',sort=document.getElementById('absenceManageSort')?.value||'date_desc';const list=sortRecords(data.filter(r=>{const hay=norm([r.id,r.submittedAt,r.name,r.jobTitle,r.email,r.category,r.mode,r.type,r.startDate,r.endDate,r.startTime,r.endTime,r.note,r.status,r.reviewerJobTitle,r.reviewedAt,r.comment].join(' '));return(!q||hay.includes(q))&&(!st||r.status===st)&&(!cat||r.category===cat)&&(!mode||r.mode===mode);}),sort);text('absenceManageCount',`${list.length} / ${data.length} rekod`);const body=document.getElementById('absenceManageRows');if(!body)return;body.innerHTML=list.length?list.map(r=>`<tr><td><b>${esc(r.name)}</b><small class="table-sub">${esc(r.jobTitle||'—')} · ${esc(r.email)} · ${esc(r.category)}</small></td><td><b>${esc(r.mode==='KEBERADAAN'?'Keberadaan':'Tidak Hadir')}</b></td><td><b>${esc(r.type)}</b></td><td>${esc(formatDateRange(r.startDate,r.endDate))}${r.mode==='KEBERADAAN'?`<small class="table-sub">${esc(r.startTime||'—')} – ${esc(r.endTime||'—')}</small>`:''}<small class="table-sub">${r.synthetic?'Dikesan:':'Hantar:'} ${esc(r.submittedAt)}</small></td><td>${esc(r.note||'—')}</td><td><span class="request-status ${absenceStatusClass(r.status)}">${esc(r.status)}</span></td><td>${r.status==='MENUNGGU'?`<div class="row-actions"><button class="action-link approve-link" onclick='openReviewAbsence(${JSON.stringify(r.id)},"DILULUSKAN")'>Lulus</button><button class="action-link warn-link" onclick='openReviewAbsence(${JSON.stringify(r.id)},"DITOLAK")'>Tolak</button></div>`:r.synthetic?'<span class="muted">Tiada permohonan</span>':`<span class="review-role-tag">${esc(r.reviewerJobTitle||'Pengurusan')}</span><small class="table-sub">Catatan: ${esc(r.comment||'—')}</small><small class="table-sub">${esc(r.reviewedAt||'—')}</small>`}</td></tr>`).join(''):'<tr><td colspan="7" class="empty-cell">Tiada rekod sepadan.</td></tr>';\n  }''','absence manage')
    s=sub(s,r"  function applyTimeReviewFilters\(\)\{.*?\n  \}",'''  function applyTimeReviewFilters(){const data=state.timeReview?.rows||[],q=norm(document.getElementById('timeReviewSearch')?.value),type=document.getElementById('timeReviewType')?.value||'',st=document.getElementById('timeReviewStatus')?.value||'',sort=document.getElementById('timeReviewSort')?.value||'date_desc';const list=sortRecords(data.filter(r=>{const hay=norm([r.name,r.jobTitle,r.email,r.category,r.date,r.type,r.session,r.recordTime,r.referenceTime,r.reviewStatus,r.reviewerJobTitle,r.comment].join(' '));return(!q||hay.includes(q))&&(!type||r.type===type)&&(!st||r.reviewStatus===st);}),sort);text('timeReviewCount',`${list.length} / ${data.length} rekod`);const body=document.getElementById('timeReviewRows');if(!body)return;body.innerHTML=list.length?list.map(r=>`<tr><td><b>${esc(r.name)}</b><small class="table-sub">${esc(r.jobTitle||'—')} · ${esc(r.email)}</small></td><td>${esc(r.date)}</td><td><span class="badge ${r.type==='LEWAT'?'lewat':'awal'}">${esc(r.type)}</span></td><td>${esc(r.session)}</td><td><b>${esc(r.recordTime)}</b></td><td>${esc(r.referenceTime||'—')}</td><td><span class="request-status ${r.reviewStatus==='DIAMBIL MAKLUM'?'approved':r.reviewStatus==='DITOLAK'?'rejected':'pending'}">${esc(r.reviewStatus)}</span></td><td>${r.reviewStatus==='BELUM DIAMBIL MAKLUM'?`<div class="row-actions"><button class="action-link approve-link" onclick='openTimeReview(${JSON.stringify(r.id)},"DIAMBIL MAKLUM")'>Diambil Maklum</button><button class="action-link warn-link" onclick='openTimeReview(${JSON.stringify(r.id)},"DITOLAK")'>Ditolak</button></div>`:`<span class="review-role-tag">${esc(r.reviewerJobTitle||'Pentadbir Sistem')}</span><small class="table-sub">Catatan: ${esc(r.comment||'—')}</small><small class="table-sub">${esc(r.reviewedAt||'—')}</small>`}</td></tr>`).join(''):'<tr><td colspan="8" class="empty-cell">Tiada rekod sepadan.</td></tr>';\n  }''','time review')
    s=one(s,"    const list=data.filter(r=>{\n      const hay=norm([r.date,r.name,r.jobTitle,r.email,r.category,r.status,r.inDistanceM,r.outDistanceM,r.inDistanceM2,r.outDistanceM2,r.source,r.editedBy,r.reason,r.inIp,r.outIp,r.inIp2,r.outIp2,r.ipCheck].join(' '));\n      return(!q||hay.includes(q))&&(!cat||r.category===cat)&&(!st||String(r.status||'').includes(st))&&(!src||r.source===src);\n    });","    const list=sortRecords(data.filter(r=>{\n      const hay=norm([r.date,r.name,r.jobTitle,r.email,r.category,r.status,r.inDistanceM,r.outDistanceM,r.inDistanceM2,r.outDistanceM2,r.source,r.editedBy,r.reason,r.inIp,r.outIp,r.inIp2,r.outIp2,r.ipCheck].join(' '));\n      return(!q||hay.includes(q))&&(!cat||r.category===cat)&&(!st||String(r.status||'').includes(st))&&(!src||r.source===src);\n    }),document.getElementById('reportSort')?.value||'name_asc');",'report sort')
    s=one(s,"    const list=data.filter(u=>{\n      const ps=userPinState(u),hay=norm([u.active?'aktif':'tidak aktif',u.name,u.jobTitle,u.email,u.category,u.isAdmin?'pentadbir sistem':'bukan admin',ps,u.s1In,u.s1Out,u.s2In,u.s2Out,u.note,u.lockedUntil,u.hasProfilePhoto?'gambar profil':'tiada gambar'].join(' '));\n      return(!q||hay.includes(q))&&(!cat||u.category===cat)&&(!active||(active==='active'?u.active:!u.active))&&(!adm||(adm==='yes'?u.isAdmin:!u.isAdmin))&&(!pw||ps===pw);\n    });","    const list=sortRecords(data.filter(u=>{\n      const ps=userPinState(u),hay=norm([u.active?'aktif':'tidak aktif',u.name,u.jobTitle,u.email,u.category,u.isAdmin?'pentadbir sistem':'bukan admin',ps,u.s1In,u.s1Out,u.s2In,u.s2Out,u.note,u.lockedUntil,u.hasProfilePhoto?'gambar profil':'tiada gambar'].join(' '));\n      return(!q||hay.includes(q))&&(!cat||u.category===cat)&&(!active||(active==='active'?u.active:!u.active))&&(!adm||(adm==='yes'?u.isAdmin:!u.isAdmin))&&(!pw||ps===pw);\n    }),document.getElementById('userSort')?.value||'name_asc');",'user sort')
    s=one(s,"async function submitTimeReview(ev,id,decision){ev.preventDefault();const comment=new FormData(ev.target).get('comment')||'';try{const r=await runServer('reviewTimeException',state.token,id,decision,comment);closeModal();toast(`${r.status} oleh ${r.reviewerName}.`,4500);state.timeReview=null;state.myCardLoaded=false;state.adminCardData=null;await loadTimeReview(true);}catch(e){handleServerError(e);}}","async function submitTimeReview(ev,id,decision){ev.preventDefault();const comment=new FormData(ev.target).get('comment')||'';try{const r=await runServer('reviewTimeException',state.token,id,decision,comment);closeModal();toast(`${r.status}.`,4500);state.timeReview=null;state.myCardLoaded=false;state.adminCardData=null;await loadTimeReview(true);}catch(e){handleServerError(e);}}",'toast')
    return s

patch_file('Index.html',index)
patch_file('Scripts.html',scripts)
p=Path('Styles.html'); s=p.read_text(encoding='utf-8');
if '.review-role-tag{' not in s:s+='\n.review-role-tag{display:inline-flex;width:max-content;margin-top:5px;padding:3px 8px;border-radius:999px;background:#eef4ff;color:#175cd3;font-size:11px;font-weight:800}.pc-time-alert{color:#b42318!important;font-weight:900!important;background:#fff1f0!important}.pc-row-lewat .pc-statement{color:#b42318;font-weight:800}.setting-subsection{margin-top:8px;padding:12px 14px;border:1px solid #d0d5dd;border-radius:12px;background:#f8fafc;display:flex;flex-direction:column;gap:3px}\n'
p.write_text(s,encoding='utf-8')
