import {google} from 'googleapis';
import {ABSENCE_HEADERS, ATT_HEADERS, DEFAULT_SETTINGS, SHEETS, TIME_REVIEW_HEADERS, TRUSTED_DEVICE_HEADERS, USER_HEADERS} from './constants';
import {dateKey, normalizeTime} from './time';
import type {AbsenceRow, AttendanceRow, Settings, SheetValue, UserRecord} from './types';

function env(name:string){const v=process.env[name];if(!v)throw new Error(`Environment variable ${name} belum ditetapkan.`);return v}
const auth=new google.auth.GoogleAuth({credentials:{client_email:process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,private_key:process.env.GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY?.replace(/\\n/g,'\n')},scopes:['https://www.googleapis.com/auth/spreadsheets','https://www.googleapis.com/auth/drive.readonly']});
const api=google.sheets({version:'v4',auth});
export const drive=google.drive({version:'v3',auth});
const spreadsheetId=()=>env('GOOGLE_SHEET_ID');
export function columnName(n:number){let s='';while(n>0){const r=(n-1)%26;s=String.fromCharCode(65+r)+s;n=Math.floor((n-1)/26)}return s}
export function normalizeEmail(v:unknown){return String(v??'').trim().toLowerCase()}
export function toBool(v:unknown){const s=String(v??'').trim().toLowerCase();return v===true||['true','1','ya','yes','✓'].includes(s)}
export async function getRows(sheet:string,range='A:ZZ'){env('GOOGLE_SERVICE_ACCOUNT_PRIVATE_KEY');const r=await api.spreadsheets.values.get({spreadsheetId:spreadsheetId(),range:`'${sheet}'!${range}`,valueRenderOption:'FORMATTED_VALUE',dateTimeRenderOption:'FORMATTED_STRING'});return (r.data.values??[]) as SheetValue[][]}
export async function appendRow(sheet:string,values:SheetValue[]){await api.spreadsheets.values.append({spreadsheetId:spreadsheetId(),range:`'${sheet}'!A:ZZ`,valueInputOption:'USER_ENTERED',insertDataOption:'INSERT_ROWS',requestBody:{values:[values]}})}
export async function appendRows(sheet:string,values:SheetValue[][]){if(!values.length)return;await api.spreadsheets.values.append({spreadsheetId:spreadsheetId(),range:`'${sheet}'!A:ZZ`,valueInputOption:'USER_ENTERED',insertDataOption:'INSERT_ROWS',requestBody:{values}})}
export async function updateRow(sheet:string,row:number,values:SheetValue[]){await api.spreadsheets.values.update({spreadsheetId:spreadsheetId(),range:`'${sheet}'!A${row}:${columnName(values.length)}${row}`,valueInputOption:'USER_ENTERED',requestBody:{values:[values]}})}
export async function updateCells(sheet:string,row:number,startColumn:number,values:SheetValue[]){if(!values.length)return;await api.spreadsheets.values.update({spreadsheetId:spreadsheetId(),range:`'${sheet}'!${columnName(startColumn)}${row}:${columnName(startColumn+values.length-1)}${row}`,valueInputOption:'USER_ENTERED',requestBody:{values:[values]}})}
export async function clearRange(sheet:string,range:string){await api.spreadsheets.values.clear({spreadsheetId:spreadsheetId(),range:`'${sheet}'!${range}`,requestBody:{}})}
export async function deleteRows(sheet:string,rows:number[]){if(!rows.length)return;const meta=await api.spreadsheets.get({spreadsheetId:spreadsheetId(),fields:'sheets.properties'});const sh=meta.data.sheets?.find((x:any)=>x.properties?.title===sheet);const sheetId=sh?.properties?.sheetId;if(sheetId==null)throw new Error(`Sheet ${sheet} tidak dijumpai.`);await api.spreadsheets.batchUpdate({spreadsheetId:spreadsheetId(),requestBody:{requests:[...rows].sort((a,b)=>b-a).map(row=>({deleteDimension:{range:{sheetId,dimension:'ROWS',startIndex:row-1,endIndex:row}}}))}})}
export function userFromRow(v:SheetValue[],row:number):UserRecord{const raw=String(v[3]??'').trim()||'PPP';return{row,active:toBool(v[0]),name:String(v[1]??'').trim(),email:normalizeEmail(v[2]),category:raw==='Pentadbir'?'Pengurusan':raw,isAdmin:toBool(v[4]),lateAfter:normalizeTime(v[5]),maxPunchIn:normalizeTime(v[6]),punchOutFrom:normalizeTime(v[7]),note:String(v[8]??''),passwordSalt:String(v[9]??''),passwordHash:String(v[10]??''),mustChangePassword:toBool(v[11]),sessionVersion:Math.max(1,Number(v[12])||1),failedLoginCount:Math.max(0,Number(v[13])||0),lockedUntil:String(v[14]??''),passwordUpdatedAt:String(v[15]??''),profilePhotoFileId:String(v[16]??''),authType:String(v[18]??'').trim().toUpperCase(),jobTitle:String(v[19]??'').trim(),s1In:normalizeTime(v[20]),s1Out:normalizeTime(v[21]),s2In:normalizeTime(v[22]),s2Out:normalizeTime(v[23])}}
export async function getUsers(){const rows=await getRows(SHEETS.USERS,`A1:${columnName(USER_HEADERS.length)}`);return rows.slice(1).map((r,i)=>userFromRow(r,i+2)).filter(u=>u.email)}
export async function getUser(email:string,activeOnly=true){const n=normalizeEmail(email);const u=(await getUsers()).find(x=>x.email===n)??null;return u&&(!activeOnly||u.active)?u:null}
export async function getSettings():Promise<Settings>{const rows=await getRows(SHEETS.SETTINGS,'A1:C');const out:Settings={...DEFAULT_SETTINGS};for(const row of rows.slice(1)){const k=String(row[0]??'').trim();if(k)out[k]=String(row[1]??'').trim()}return out}
export async function saveSettings(next:Settings){const rows=await getRows(SHEETS.SETTINGS,'A1:C');const existing=rows.slice(1).map(r=>[String(r[0]??''),String(r[1]??''),String(r[2]??'')]);const map=new Map(existing.map((r,i)=>[r[0],i]));for(const [k,v] of Object.entries(next)){const i=map.get(k);if(i==null){map.set(k,existing.length);existing.push([k,v,''])}else existing[i][1]=v}await api.spreadsheets.values.update({spreadsheetId:spreadsheetId(),range:`'${SHEETS.SETTINGS}'!A2:C${existing.length+1}`,valueInputOption:'USER_ENTERED',requestBody:{values:existing}})}
export async function attendanceRows(from?:string,to?:string){const rows=await getRows(SHEETS.ATTENDANCE,`A1:${columnName(ATT_HEADERS.length)}`);return rows.slice(1).map((v,i):AttendanceRow=>({row:i+2,values:[...v,...Array(Math.max(0,ATT_HEADERS.length-v.length)).fill('')],date:dateKey(v[0]),email:normalizeEmail(v[1])})).filter(r=>r.email&&r.date&&(!from||r.date>=from)&&(!to||r.date<=to))}
export async function absenceRows(){const rows=await getRows(SHEETS.ABSENCE,`A1:${columnName(ABSENCE_HEADERS.length)}`);return rows.slice(1).map((v,i):AbsenceRow=>({row:i+2,id:String(v[0]??''),submittedAt:String(v[1]??''),email:normalizeEmail(v[2]),name:String(v[3]??''),category:String(v[4]??''),type:String(v[5]??''),startDate:dateKey(v[6]),endDate:dateKey(v[7]),note:String(v[8]??''),status:String(v[9]??'MENUNGGU'),reviewedBy:normalizeEmail(v[10]),reviewedAt:String(v[11]??''),comment:String(v[12]??''),updatedAt:String(v[13]??''),mode:String(v[14]??'TIDAK_HADIR').toUpperCase()==='KEBERADAAN'?'KEBERADAAN':'TIDAK_HADIR',startTime:normalizeTime(v[15]),endTime:normalizeTime(v[16]),jobTitle:String(v[17]??'')})).filter(r=>r.id&&r.email)}
export async function timeReviewRows(){const rows=await getRows(SHEETS.TIME_REVIEW,`A1:${columnName(TIME_REVIEW_HEADERS.length)}`);return rows.slice(1).map((v,i)=>({row:i+2,id:String(v[0]??''),createdAt:String(v[1]??''),date:dateKey(v[2]),email:normalizeEmail(v[3]),name:String(v[4]??''),jobTitle:String(v[5]??''),category:String(v[6]??''),type:String(v[7]??''),session:Number(v[8])||1,recordTime:normalizeTime(v[9]),referenceTime:normalizeTime(v[10]),reviewStatus:String(v[11]??'BELUM DIAMBIL MAKLUM'),reviewedBy:normalizeEmail(v[12]),reviewerName:String(v[13]??''),reviewedAt:String(v[14]??''),comment:String(v[15]??'')})).filter(r=>r.id)}
export async function trustedDeviceRows(){const rows=await getRows(SHEETS.TRUSTED_DEVICES,`A1:${columnName(TRUSTED_DEVICE_HEADERS.length)}`);return rows.slice(1).map((v,i)=>({row:i+2,id:String(v[0]??'').trim().toLowerCase(),email:normalizeEmail(v[1]),name:String(v[2]??''),platform:String(v[3]??''),browser:String(v[4]??''),ip:String(v[5]??''),createdAt:String(v[6]??''),lastSeen:String(v[7]??''),expiresAt:String(v[8]??''),active:toBool(v[9]),sessionVersion:Math.max(1,Number(v[10])||1),hash:String(v[11]??''),reason:String(v[12]??'')})).filter(r=>r.id&&r.email)}
export async function replaceReportSheet(values:SheetValue[][]){await clearRange(SHEETS.REPORT,'A:Z');if(values.length)await api.spreadsheets.values.update({spreadsheetId:spreadsheetId(),range:`'${SHEETS.REPORT}'!A1`,valueInputOption:'USER_ENTERED',requestBody:{values}})}
