import {NextRequest,NextResponse} from 'next/server';
import {ABSENCE_TYPES,PRESENCE_TYPES,SHEETS} from '@/lib/constants';
import {absenceManagement,absencePublic,adminBootstrap,cancelAbsence,dailyReport,dailyReportEmailRun,getTimeReviews,loginLog,myMonth,ownAbsence,periodReport,presenceExpiryRun,publicSettings,publicUser,punch,punchReminderRun,repairAttendanceDuplicates,resetUserPin,reviewAbsence,reviewTime,revokeDevice,revokeUserDevices,saveAttendance,saveUser,submitAbsence,summarizeReport,todayForUser,unlockUser,updateSettings,userDevices,writeReportSheet} from '@/lib/core';
import {drive,getSettings,getUser,getUsers,normalizeEmail} from '@/lib/sheets';
import {clearAuthCookies,currentSession,failedLogin,isLocked,issueSession,registerDevice,requireAdmin,requireManagement,requireUser,resetLoginFailures,revokeCurrentDevice,setAuthCookies,setPin,verifyPin} from '@/lib/security';
import {tablePdf} from '@/lib/pdf';
import {todayKey,validateDate} from '@/lib/time';

export const runtime='nodejs';
export const dynamic='force-dynamic';
const ok=(data:any,status=200)=>NextResponse.json(data,{status});
function err(e:unknown){const m=e instanceof Error?e.message:String(e);const status=m==='UNAUTHORIZED'?401:m==='FORBIDDEN'?403:400;return ok({error:status===401?'Sesi tamat. Sila log masuk semula.':status===403?'Akses tidak dibenarkan.':m},status)}
async function payload(req:NextRequest){try{return await req.json()}catch{return{}}}
function ip(req:NextRequest){return(req.headers.get('x-forwarded-for')||req.headers.get('x-real-ip')||'').split(',')[0].trim().replace(/^::ffff:/,'')}
function ua(req:NextRequest){return req.headers.get('user-agent')||''}
async function pathOf(ctx:{params:Promise<{route?:string[]}>}){return((await ctx.params).route||[]).join('/')}
function cronAllowed(req:NextRequest){const sec=process.env.CRON_SECRET;if(!sec)return process.env.NODE_ENV!=='production';return req.headers.get('authorization')===`Bearer ${sec}`}

async function handle(req:NextRequest,ctx:{params:Promise<{route?:string[]}>}){try{const path=await pathOf(ctx),method=req.method;
  if(path==='health')return ok({ok:true,service:'eKeberadaan',timezone:'Asia/Kuala_Lumpur'});
  if(path==='auth/account'&&method==='GET'){const email=normalizeEmail(req.nextUrl.searchParams.get('email')),u=await getUser(email,true);if(!u)return ok({exists:false});return ok({exists:true,name:u.name,needsSetup:!u.passwordHash||u.authType!=='PIN_V1'||u.mustChangePassword,locked:isLocked(u)});}
  if(path==='auth/setup'&&method==='POST'){const b=await payload(req),email=normalizeEmail(b.email),pinv=String(b.pin||''),confirm=String(b.confirmPin||'');if(pinv!==confirm)throw new Error('Pengesahan PIN tidak sepadan.');const u=await getUser(email,true);if(!u)throw new Error('Akaun DELIMa tidak didaftarkan.');if(u.passwordHash&&u.authType==='PIN_V1'&&!u.mustChangePassword)throw new Error('PIN telah tersedia. Sila log masuk.');const changed=await setPin(u,pinv,false),d=await registerDevice(changed,ua(req),ip(req)),token=await issueSession(changed,d.id);await setAuthCookies(token,d.credential);await loginLog(changed,ip(req),ua(req),'PIN_DISEDIAKAN','First-time / reset PIN');return ok({ok:true,user:publicUser(changed)});}
  if(path==='auth/login'&&method==='POST'){const b=await payload(req),email=normalizeEmail(b.email),pinv=String(b.pin||''),u=await getUser(email,true);if(!u){await loginLog(null,ip(req),ua(req),'GAGAL','Akaun tidak didaftarkan');throw new Error('Emel atau PIN tidak sah.');}if(isLocked(u))throw new Error('Akaun dikunci sementara selepas terlalu banyak cubaan.');if(!verifyPin(pinv,u)){const f=await failedLogin(u);await loginLog(u,ip(req),ua(req),'GAGAL',f.locked?'Akaun dikunci':'PIN salah');throw new Error(f.locked?'Akaun dikunci 15 minit.':'Emel atau PIN tidak sah.');}await resetLoginFailures(u);const fresh=(await getUser(email,true))!,d=await registerDevice(fresh,ua(req),ip(req)),token=await issueSession(fresh,d.id);await setAuthCookies(token,d.credential);await loginLog(fresh,ip(req),ua(req),'BERJAYA','Login PIN');return ok({ok:true,user:publicUser(fresh)});}
  if(path==='auth/logout'&&method==='POST'){await revokeCurrentDevice();return ok({ok:true});}
  if(path==='me'&&method==='GET'){const{user}=await requireUser(),s=await getSettings(),today=await todayForUser(user);return ok({user:publicUser(user),today,settings:publicSettings(s)});}
  if(path==='punch'&&method==='POST'){const{user}=await requireUser(),b=await payload(req);return ok(await punch(user,String(b.type||''),b.location,ip(req)));}
  if(path==='attendance/month'&&method==='GET'){const{user}=await requireUser(),month=req.nextUrl.searchParams.get('month')||todayKey().slice(0,7);return ok(await myMonth(user,month));}
  if(path==='absence'&&method==='GET'){const{user}=await requireUser();return ok({records:await ownAbsence(user),types:ABSENCE_TYPES,presenceTypes:PRESENCE_TYPES});}
  if(path==='absence'&&method==='POST'){const{user}=await requireUser();return ok(await submitAbsence(user,await payload(req)));}
  if(path==='absence/cancel'&&method==='POST'){const{user}=await requireUser(),b=await payload(req);return ok(await cancelAbsence(user,String(b.id||'')));}
  if(path==='absence/public'&&method==='GET'){await requireUser();const from=validateDate(req.nextUrl.searchParams.get('from')||todayKey()),to=validateDate(req.nextUrl.searchParams.get('to')||from);return ok({from,to,records:await absencePublic(from,to)});}
  if(path==='absence/manage'&&method==='GET'){await requireManagement();const from=validateDate(req.nextUrl.searchParams.get('from')||todayKey()),to=validateDate(req.nextUrl.searchParams.get('to')||from);return ok({from,to,records:await absenceManagement(from,to)});}
  if(path==='absence/review'&&method==='POST'){const{user}=await requireManagement(),b=await payload(req);return ok(await reviewAbsence(user,String(b.id||''),String(b.decision||''),String(b.comment||'')));}
  if(path==='time-review'&&method==='GET'){await requireAdmin();const from=validateDate(req.nextUrl.searchParams.get('from')||todayKey()),to=validateDate(req.nextUrl.searchParams.get('to')||from);return ok({from,to,records:await getTimeReviews(from,to)});}
  if(path==='time-review/review'&&method==='POST'){const{user}=await requireAdmin(),b=await payload(req);return ok(await reviewTime(user,String(b.id||''),String(b.decision||''),String(b.comment||'')));}
  if(path==='admin/bootstrap'&&method==='GET'){await requireAdmin();const date=validateDate(req.nextUrl.searchParams.get('date')||todayKey());return ok(await adminBootstrap(date));}
  if(path==='admin/users'&&method==='GET'){await requireAdmin();return ok({users:(await getUsers()).map(publicUser)});}
  if(path==='admin/users'&&method==='POST'){const{user}=await requireAdmin();return ok({ok:true,user:await saveUser(user,await payload(req))});}
  if(path==='admin/users/reset-pin'&&method==='POST'){const{user}=await requireAdmin(),b=await payload(req);return ok(await resetUserPin(user,String(b.email||'')));}
  if(path==='admin/users/unlock'&&method==='POST'){const{user}=await requireAdmin(),b=await payload(req);return ok(await unlockUser(user,String(b.email||'')));}
  if(path==='admin/devices'&&method==='GET'){await requireAdmin();return ok({records:await userDevices(req.nextUrl.searchParams.get('email')||'')});}
  if(path==='admin/devices/revoke'&&method==='POST'){const{user}=await requireAdmin(),b=await payload(req);return ok(await revokeDevice(user,String(b.id||'')));}
  if(path==='admin/devices/revoke-all'&&method==='POST'){const{user}=await requireAdmin(),b=await payload(req);return ok(await revokeUserDevices(user,String(b.email||'')));}
  if(path==='admin/settings'&&method==='GET'){await requireAdmin();return ok({settings:publicSettings(await getSettings())});}
  if(path==='admin/settings'&&method==='POST'){const{user}=await requireAdmin();return ok({ok:true,settings:await updateSettings(user,await payload(req))});}
  if(path==='admin/attendance'&&method==='GET'){await requireAdmin();const date=validateDate(req.nextUrl.searchParams.get('date')||todayKey()),rows=await dailyReport(date);return ok({date,records:rows,summary:summarizeReport(rows)});}
  if(path==='admin/attendance'&&method==='POST'){const{user}=await requireAdmin();return ok(await saveAttendance(user,await payload(req)));}
  if(path==='admin/repair'&&method==='POST'){const{user}=await requireAdmin(),result=await repairAttendanceDuplicates();return ok({ok:true,...result,actor:user.email});}
  if(path==='admin/report/sheet'&&method==='POST'){await requireAdmin();const b=await payload(req);return ok(await writeReportSheet(validateDate(b.date||todayKey())));}
  if(path==='admin/report'&&method==='GET'){await requireAdmin();const from=validateDate(req.nextUrl.searchParams.get('from')||todayKey()),to=validateDate(req.nextUrl.searchParams.get('to')||from),rows=await periodReport(from,to,{category:req.nextUrl.searchParams.get('category')||'',status:req.nextUrl.searchParams.get('status')||'',email:req.nextUrl.searchParams.get('email')||''});return ok({from,to,records:rows});}
  if(path==='report/pdf'&&method==='GET'){const session=await requireUser(),kind=req.nextUrl.searchParams.get('kind')||'period',from=validateDate(req.nextUrl.searchParams.get('from')||todayKey()),to=validateDate(req.nextUrl.searchParams.get('to')||from);let title='',headers:string[]=[],rows:any[][]=[];if(kind==='absence'){const data=session.user.isAdmin||session.user.category==='Pengurusan'?await absenceManagement(from,to):await absencePublic(from,to);title=`Tidak Hadir / Keberadaan ${from} hingga ${to}`;headers=['Tarikh','Nama','Mod','Jenis','Masa','Status','Catatan'];rows=data.map(r=>[r.startDate,r.name,r.mode,r.type,`${r.startTime||''}-${r.endTime||''}`,r.status,r.note||''])}else if(kind==='time'){if(!session.user.isAdmin)throw new Error('FORBIDDEN');const data=await getTimeReviews(from,to);title=`Semakan Lewat / Balik Awal ${from} hingga ${to}`;headers=['Tarikh','Nama','Jenis','Sesi','Rekod','Rujukan','Status','Pelulus'];rows=data.map(r=>[r.date,r.name,r.type,r.session,r.recordTime,r.referenceTime,r.reviewStatus,r.reviewerName])}else{if(!session.user.isAdmin)throw new Error('FORBIDDEN');const data=await periodReport(from,to);title=`Laporan Kehadiran / Keberadaan ${from} hingga ${to}`;headers=['Tarikh','Nama','Kategori','Status','M1','K1','M2','K2','Sebab'];rows=data.map(r=>[r.date,r.name,r.category,r.status,r.inTime,r.outTime,r.inTime2,r.outTime2,r.reason||''])}const pdf=await tablePdf(title,headers,rows);return new Response(new Uint8Array(pdf),{headers:{'content-type':'application/pdf','content-disposition':`attachment; filename="eKeberadaan_${kind}_${from}_${to}.pdf"`}});}
  if(path==='profile'&&method==='GET'){const{user}=await requireUser(),email=normalizeEmail(req.nextUrl.searchParams.get('email')||user.email);if(email!==user.email&&!user.isAdmin)throw new Error('FORBIDDEN');const target=await getUser(email,false);if(!target?.profilePhotoFileId)return new Response(null,{status:404});const f=await drive.files.get({fileId:target.profilePhotoFileId,alt:'media'},{responseType:'arraybuffer'});return new Response(new Uint8Array(f.data as ArrayBuffer),{headers:{'content-type':'image/jpeg','cache-control':'private, max-age=3600'}});}
  if(path.startsWith('cron/')){if(!cronAllowed(req))return ok({error:'Forbidden'},403);if(path==='cron/punch-reminder')return ok(await punchReminderRun());if(path==='cron/daily-report')return ok(await dailyReportEmailRun());if(path==='cron/presence-expiry')return ok(await presenceExpiryRun());}
  return ok({error:'Endpoint tidak dijumpai.'},404);
}catch(e){return err(e)}}
export const GET=handle;export const POST=handle;export const PUT=handle;export const DELETE=handle;
